[project]
name = "tetrika-junior-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "isort>=6.0.1",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
